### PR TITLE
Adding an about page

### PR DESCRIPTION
**Pull request by aarongustafson**
@webmaxru @Snugug Draft about content attached. Needs some styles.

### CODE REVIEW

**Comment by webmaxru** [comment]
Hi! I changed formatting a bit to follow CoC page schema, added one style (for `blockquote`) and fixed the build. Here is the page: https://deploy-preview-9--peaceful-darwin-86c101.netlify.app/about/

**Comment by webmaxru** [comment]
@aarongustafson great work on the content!

**Review by webmaxru — APPROVED** [review]

**Comment by aarongustafson** [comment]
LGTM

**Comment by aarongustafson** [comment]
@Snugug When you have a moment, give this a look.

**Pull request merged**
